### ISSUE TITLE
question: How to see the changes for an API across time

### ISSUE THREAD

**Issue by gedw99** [simonw/help-scraper#11]
This is very useful actually. 

I have a use case that is a bit different perhaps. I am not even sure this is useful to others so please comment...

Most users want the commits to see when an API changes at a high granularity, so they can react to those changes as they occur. But what if you want to see the changes that occured over say 1 month or a year in a one page view ? Its use case is more for a summary level view where you want to see a flavour of what is going on for a year or so. 

For example, when i look at https://github.com/simonw/help-scraper/commits/main/flyctl/fly.graphql i have to click through every change to see it. 

Brainstorming ideas on this, i feel that it's not a technical problem but an information architecture problem in that  it's hard to design a markdown page that displays all the changes on a single page.   Technically, there are probably some tools out there that can take a git commit log and produce a markup page that is a summary - we could run that tool as part of the github actions.

**Comment by simonw** [comment]
The `git blame` page might be useful here: https://github.com/simonw/help-scraper/blame/main/flyctl/fly.graphql

**Comment by simonw** [comment]
I'm closing this for now, but if you come up with a better solution here I'd love to hear about it in a comment on this issue!

**Comment by gedw99** [comment]
thanks - blame works:  https://github.com/simonw/help-scraper/blame/main/flyctl/fly.graphql

I can put a GUi in front of that with a link to each one blame link.
