### ISSUE TITLE
Don't record SQLite if only a version bump

### ISSUE THREAD

**Issue by simonw** [simonw/help-scraper#13]
Not sure the best way to do this. I'd like to avoid lots of commits that just look like this one: https://github.com/simonw/help-scraper/commit/f62510f0125f9ad11163be9123d5d231d7712716

**Comment by simonw** [comment]
I could add logic to the script which reads the previous file and only writes out if more than the version has changed: https://github.com/simonw/help-scraper/blob/main/sqlite3_help.py

**Comment by RonnyPfannschmidt** [comment]
In regendoc I use the concept of normalizers, which replace chatty parts of output with a indicative string

Perhaps this could be done here as well

**Comment by simonw** [comment]
I'm going to solve this by looking for this line:

    Version: `3.39.0 2022-03-22 19:41:55 67d8b434f628d44...`

And converting it to this before saving it:

    Version: `3.39.0`

**Comment by simonw** [comment]
> In regendoc I use the concept of normalizers, which replace chatty parts of output with a indicative string

I hadn't seen https://github.com/pytest-dev/regendoc - looks very handy!

Found the substituters in here: https://github.com/pytest-dev/regendoc/blob/e6013a994fb1577c557591b5ae1cee56a0c88380/src/regendoc/substitute.py
